/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as QuizzesIndexImport } from './routes/quizzes/index'
import { Route as QuizzesQuizIdImport } from './routes/quizzes/$quizId'
import { Route as QuizResultsQuizIdImport } from './routes/quiz-results/$quizId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuizzesIndexRoute = QuizzesIndexImport.update({
  path: '/quizzes/',
  getParentRoute: () => rootRoute,
} as any)

const QuizzesQuizIdRoute = QuizzesQuizIdImport.update({
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRoute,
} as any)

const QuizResultsQuizIdRoute = QuizResultsQuizIdImport.update({
  path: '/quiz-results/$quizId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quiz-results/$quizId': {
      id: '/quiz-results/$quizId'
      path: '/quiz-results/$quizId'
      fullPath: '/quiz-results/$quizId'
      preLoaderRoute: typeof QuizResultsQuizIdImport
      parentRoute: typeof rootRoute
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdImport
      parentRoute: typeof rootRoute
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  QuizResultsQuizIdRoute,
  QuizzesQuizIdRoute,
  QuizzesIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quiz-results/$quizId",
        "/quizzes/$quizId",
        "/quizzes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quiz-results/$quizId": {
      "filePath": "quiz-results/$quizId.tsx"
    },
    "/quizzes/$quizId": {
      "filePath": "quizzes/$quizId.tsx"
    },
    "/quizzes/": {
      "filePath": "quizzes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
